name: "Release Build"

on:
  push:
    tags:
      - "v*"

jobs:
  # Prepare release information that will be used by all the build workflows
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ github.ref_name }}
      release_name: "anime-management ${{ github.ref_name }}"
      release_body: "See the assets to download and install this version."
      draft: true
      prerelease: false
    steps:
      - name: Set up release information
        run: echo "Preparing release ${{ github.ref_name }}"

  # Build Linux x64 and ARM64
  build-linux:
    needs: prepare-release
    uses: ./.github/workflows/build-linux.yml
    with:
      tag_name: ${{ needs.prepare-release.outputs.tag_name }}
      release_name: ${{ needs.prepare-release.outputs.release_name }}
      release_body: ${{ needs.prepare-release.outputs.release_body }}
      draft: ${{ needs.prepare-release.outputs.draft }}
      prerelease: ${{ needs.prepare-release.outputs.prerelease }}
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build macOS Intel and Apple Silicon
  build-macos:
    needs: prepare-release
    uses: ./.github/workflows/build-macos.yml
    with:
      tag_name: ${{ needs.prepare-release.outputs.tag_name }}
      release_name: ${{ needs.prepare-release.outputs.release_name }}
      release_body: ${{ needs.prepare-release.outputs.release_body }}
      draft: ${{ needs.prepare-release.outputs.draft }}
      prerelease: ${{ needs.prepare-release.outputs.prerelease }}
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build Windows
  build-windows:
    needs: prepare-release
    uses: ./.github/workflows/build-windows.yml
    with:
      tag_name: ${{ needs.prepare-release.outputs.tag_name }}
      release_name: ${{ needs.prepare-release.outputs.release_name }}
      release_body: ${{ needs.prepare-release.outputs.release_body }}
      draft: ${{ needs.prepare-release.outputs.draft }}
      prerelease: ${{ needs.prepare-release.outputs.prerelease }}
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build Android
  build-android:
    needs: prepare-release
    uses: ./.github/workflows/build-android.yml
    with:
      tag_name: ${{ needs.prepare-release.outputs.tag_name }}
      release_name: ${{ needs.prepare-release.outputs.release_name }}
      release_body: ${{ needs.prepare-release.outputs.release_body }}
      draft: ${{ needs.prepare-release.outputs.draft }}
      prerelease: ${{ needs.prepare-release.outputs.prerelease }}
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

  # Build iOS
  build-ios:
    needs: prepare-release
    uses: ./.github/workflows/build-ios.yml
    with:
      tag_name: ${{ needs.prepare-release.outputs.tag_name }}
      release_name: ${{ needs.prepare-release.outputs.release_name }}
      release_body: ${{ needs.prepare-release.outputs.release_body }}
      draft: ${{ needs.prepare-release.outputs.draft }}
      prerelease: ${{ needs.prepare-release.outputs.prerelease }}
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
      APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
